image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  tags:
    - pwmt
  script:
    - pip install -r requirements.txt
    - python run.py freeze
  artifacts:
    paths:
      - public
  only:
    - master
